site_name: W3F Research
docs_dir: 'docs'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjax-config.js

markdown_extensions:
    - mdx_math
